2020-05-05 16:43:32,145 ERROR: Exception on /index [GET] [in /Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/zhangbai/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhangbai/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/zhangbai/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/zhangbai/microblog/app/templates/index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-05 16:45:28,901 ERROR: Exception on /index [GET] [in /Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/zhangbai/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhangbai/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/zhangbai/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/zhangbai/microblog/app/templates/index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-05 16:45:33,959 ERROR: Exception on /index [GET] [in /Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/zhangbai/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhangbai/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/zhangbai/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/zhangbai/microblog/app/templates/index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-05 17:31:23,929 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 17:39:57,325 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-07 22:56:54,610 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
